// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dugflnxawpzityaklyzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Z2Zsbnhhd3B6aXR5YWtseXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTMxMDUsImV4cCI6MjA2OTc4OTEwNX0.r86WuDbDH4aWgvpKE5jllL9RPI7fBCFnbmEZWkp3CD0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});